import Head from 'next/head'
import Image from 'next/image'
import Banner from '../components/Banner'
import Header from '../components/Header'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Ellystore</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <div className="ax-w-screen-2xl mx-auto"   >
        <Banner/>
      </div>
      

      
    </div>
  )
}
